import discord

class Emoji:
    firstpage_emoji = discord.PartialEmoji.from_str("⏪")
    prevpage_emoji = discord.PartialEmoji.from_str("⬅️")
    nextpage_emoji = discord.PartialEmoji.from_str("➡️")
    skip_emoji = lastpage_emoji = discord.PartialEmoji.from_str("⏩")
    pause_emoji = discord.PartialEmoji.from_str("⏸️")
    play_emoji = discord.PartialEmoji.from_str("▶️")
    stop_emoji = discord.PartialEmoji.from_str("⏹️")
    skip_emoji = discord.PartialEmoji.from_str("⏩")
    repeat_emoji = discord.PartialEmoji.from_str("🔁")
    repeat_sing_emoji = discord.PartialEmoji.from_str("🔂")
    shuffle_emoji = discord.PartialEmoji.from_str("🔀")
    bulb_emoji = discord.PartialEmoji.from_str("💡")
    queue_emoji = discord.PartialEmoji.from_str("🗒️")
    leave_emoji = discord.PartialEmoji.from_str("📤")
    search_emoji = discord.PartialEmoji.from_str("🔎")
    end_emoji = discord.PartialEmoji.from_str("❎")
    done_emoji = discord.PartialEmoji.from_str("✅")
    loading_emoji = discord.PartialEmoji.from_str("<a:loading:696701361504387212>")
    caution_emoji = discord.PartialEmoji.from_str("⚠️")
    youtube_emoji = discord.PartialEmoji.from_str("<:youtube:1010812724009242745>")
    soundcloud_emoji = discord.PartialEmoji.from_str("<:soundcloud:1010812662155837511>")
    spotify_emoji = discord.PartialEmoji.from_str("<:spotify:1010844746647883828>")
    rescue_emoji = discord.PartialEmoji.from_str("🛟")
    document_emoji = discord.PartialEmoji.from_str("📝")